---

name: Master CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  master_ci_cd:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecutar pruebas
      - name: Run tests
        run: |
          python manage.py test

      # 5. Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t danielmatt/criticroute_api:develop .
